=== AshinX/xml_state_machine/src/main/resources/state-action-1.2.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="state-action">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="states" maxOccurs="unbounded"/>
                <xs:element ref="operations" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="states">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="state" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attribute ref="statusFiledName"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="operations">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="operation"/>
            </xs:choice>
            <xs:attribute ref="id"/>
            <xs:attribute ref="name"/>
        </xs:complexType>

    </xs:element>



    <xs:element name="state">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="operations" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute ref="id"/>
                        <xs:attribute ref="ref"/>
                        <xs:attribute ref="to"/>
                    </xs:complexType>
                </xs:element>
                <xs:element ref="operation"/>
            </xs:choice>
            <xs:attribute ref="i18n"/>
            <xs:attribute ref="name"/>
            <xs:attribute name="isEnd" type="xs:boolean"/>
            <xs:attribute name="isStart" type="xs:boolean"/>
            <xs:attribute ref="id" use="required"/>
            <xs:attribute ref="value"/>
        </xs:complexType>
    </xs:element>



    <xs:element name="operation">
        <xs:complexType>
            <xs:attribute ref="id"/>
            <xs:attribute ref="i18n" use="required"/>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="url"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="duration" type="xs:duration"></xs:element>
    <xs:element name="date" type="xs:string"></xs:element>
    <xs:attribute name="statusFiledName" type="xs:token"/>
    <xs:attribute name="name" type="xs:token"/>
    <xs:attribute name="i18n" type="xs:string"/>
    <xs:attribute name="url" type="xs:anyURI"/>
    <xs:attribute name="ref" type="xs:token"/>
    <xs:attribute name="id" type="xs:token"/>
    <xs:attribute name="to" type="xs:token"/>
    <xs:attribute name="value" type="xs:string"/>
    <xs:attribute name="operation" type="xs:string"/>
</xs:schema>

=== AshinX/xml_state_machine/src/main/resources/state-action.xml
<?xml version="1.0" encoding="UTF-8"?>
<state-action xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="state-action-1.2.xsd">

    <operations id="beikaifada" name="被开发打" >
            <operation name="beikaifada" i18n="被开发打" url="/beikaifada"/>
    </operations>
    <operations id="yangshangchenggong" name="养伤成功" >
            <operation name="yangshangchenggong" i18n="养伤成功"  url="/yangshangchenggong"/>
    </operations>
    <operations id="yangshangshibai" name="养伤失败" >
            <operation name="yangshangshibai" i18n="养伤失败" url="/yangshangshibai"/>
    </operations>
    <operations id="lingdaobumanyiduini" name="领导不满意怼你" >
            <operation name="lingdaobumanyiduini" i18n="领导不满意怼你" url="/lingdaobumanyiduini"/>
    </operations>
    <operations id="yangshangchenggonggaixuqiuchenggong" name="养伤成功改需求成功" >
            <operation name="yangshangchenggonggaixuqiuchenggong" i18n="养伤成功改需求成功" url="/yangshangchenggonggaixuqiuchenggong"/>
    </operations>
    <operations id="gaixuqiuchenggong" name="修改需求成功" >
            <operation name="gaixuqiuchenggong" i18n="修改需求成功" url="/gaixuqiuchenggong"/>
    </operations>
    <operations id="lingdaobumanyi" name="领导不满意" >
            <operation name="lingdaobumanyi" i18n="领导不满意" url="/lingdaobumanyi"/>
    </operations>
    <operations id="gaixuqiu" name="改需求" >
            <operation name="gaixuqiu" i18n="改需求" url="/gaixuqiu"/>
    </operations>
    <operations id="siwang" name="死亡" >
        <operation name="siwang" i18n="改需求" url="/siwang"/>
    </operations>

    <!-- 状态机主要流程 -->
    <states statusFiledName="status">
        <state id="startstate" name="startstate" i18n="开始">
           <operations ref="gaixuqiu" to="gaixuqiustate"/>
        </state>
        <state id="gaixuqiustate" name="gaixuqiustate" i18n="改需求">
            <operations ref="beikaifada" id="beikaifada" to="yangshangstate"/>
            <operations ref="gaixuqiuchenggong" id="gaixuqiuchenggong" to="zuohuibaostate"/>
        </state>
        <state id="yangshangstate" name="yangshangstate" i18n="养伤">
            <operations ref="yangshangshibai" id="yangshangshibai" to="siwangstate"/>
            <operations ref="yangshangchenggong" id="yangshangchenggong" to="gaixuqiustate"/>
            <operations ref="yangshangchenggonggaixuqiuchenggong" id="yangshangchenggonggaixuqiuchenggong" to="zuohuibaostate"/>
        </state>
        <state id="zuohuibaostate" name="zuohuibaostate" i18n="做汇报">
            <operations ref="lingdaobumanyi" id="lingdaobumanyi" to="gaixuqiustate"/>
            <operations ref="lingdaobumanyiduini" id="lingdaobumanyiduini" to="yangshangstate"/>
        </state>
        <state id="siwangstate" name="siwangstate" i18n="死亡">
            <operations ref="siwang" id="siwang" to="siwangstate"/>
        </state>
    </states>

</state-action>
